version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: logitrack
    restart: always
    environment:
      POSTGRES_USER: logitrack_user
      POSTGRES_PASSWORD: H@icktv1882k
      POSTGRES_DB: logitrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: