spring:
    application:
        name: logitrack-api-service
    datasource:
        url: jdbc:postgresql://localhost:5432/logitrack
        username: logitrack_user
        password: H@icktv1882k
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
